Repository frappe/crm, pull requests merged in 2025-04, with the labels that each got.

#712 feat: Dynamic Link field support
  frontend/src/components/Controls/Grid.vue
  frontend/src/components/Controls/Link.vue
  frontend/src/components/FieldLayout/Field.vue
  frontend/src/components/SidePanelLayout.vue
Labels: support

#742 revert: restrict app in apps page if no access to FCRM module
  crm/api/__init__.py
Labels: backport main-hotfix

#726 fix: export logic
  frontend/src/components/ListViews/CallLogsListView.vue
  frontend/src/components/ListViews/ContactsListView.vue
  frontend/src/components/ListViews/DealsListView.vue
  frontend/src/components/ListViews/EmailTemplatesListView.vue
  frontend/src/components/ListViews/LeadsListView.vue
  frontend/src/components/ListViews/OrganizationsListView.vue
  frontend/src/components/ListViews/TasksListView.vue
  frontend/src/components/ViewControls.vue
  frontend/src/pages/CallLogs.vue
  frontend/src/pages/Contacts.vue
  frontend/src/pages/Deals.vue
  frontend/src/pages/EmailTemplates.vue
  frontend/src/pages/Leads.vue
  frontend/src/pages/Organizations.vue
  frontend/src/pages/Tasks.vue
Labels: backport main-hotfix

#761 fix: mark data tab form dirty by watching field updates
  frontend/src/components/Activities/DataFields.vue
  frontend/src/pages/Deal.vue
  frontend/src/pages/Lead.vue
Labels: support, backport main-hotfix

#771 fix: contact page not loading
  crm/api/contact.py
  frontend/src/pages/Contact.vue
  frontend/src/pages/Organization.vue
Labels: support, backport main-hotfix

#776 chore: add localization support for email account settings
  frontend/src/components/Settings/EmailAccountCard.vue
  frontend/src/components/Settings/EmailAccountList.vue
  frontend/src/components/Settings/EmailAdd.vue
  frontend/src/components/Settings/EmailEdit.vue
  frontend/src/components/Settings/emailConfig.js
Labels: backport main-hotfix

#781 fix: international call log issue
  crm/integrations/api.py
Labels: backport main-hotfix
