Repository frappe/crm, pull requests merged in 2025-09, with the labels that each got.

#1198 Added support for outgoing whatsapp messages from other apps
  crm/api/whatsapp.py
Labels: backport main-hotfix

#1220 chore: sync translations from crowdin
  crm/locale/ar.po
  crm/locale/bs.po
  crm/locale/cs.po
  crm/locale/da.po
  crm/locale/de.po
  crm/locale/eo.po
  crm/locale/es.po
  crm/locale/fa.po
  crm/locale/fr.po
  crm/locale/hr.po
  crm/locale/hu.po
  crm/locale/id.po
  crm/locale/it.po
  crm/locale/nb.po
  crm/locale/nl.po
  crm/locale/pl.po
  crm/locale/pt.po
  crm/locale/pt_BR.po
  crm/locale/ru.po
  crm/locale/sr.po
  crm/locale/sr_CS.po
  crm/locale/sv.po
  crm/locale/th.po
  crm/locale/tr.po
  crm/locale/vi.po
  crm/locale/zh.po
Labels: backport main-hotfix, translation

#1231 chore: update POT file
  crm/locale/main.pot
Labels: backport main

#1237 chore: sync translations from crowdin
  crm/locale/ar.po
  crm/locale/bs.po
  crm/locale/cs.po
  crm/locale/da.po
  crm/locale/de.po
  crm/locale/eo.po
  crm/locale/es.po
  crm/locale/fa.po
  crm/locale/fr.po
  crm/locale/hr.po
  crm/locale/hu.po
  crm/locale/id.po
  crm/locale/it.po
  crm/locale/nb.po
  crm/locale/nl.po
  crm/locale/pl.po
  crm/locale/pt.po
  crm/locale/pt_BR.po
  crm/locale/ru.po
  crm/locale/sr.po
  crm/locale/sr_CS.po
  crm/locale/sv.po
  crm/locale/th.po
  crm/locale/tr.po
  crm/locale/vi.po
  crm/locale/zh.po
Labels: backport main-hotfix, translation

#1252 fix: paddings and labels
  frontend/src/components/Settings/AssignmentRules/AssigneeRules.vue
  frontend/src/components/Settings/AssignmentRules/AssignmentRuleView.vue
  frontend/src/components/Settings/AssignmentRules/AssignmentRules.vue
  frontend/src/components/Settings/EmailTemplate/EditEmailTemplate.vue
  frontend/src/components/Settings/EmailTemplate/NewEmailTemplate.vue
  frontend/src/components/Settings/General/BrandSettings.vue
  frontend/src/components/Settings/General/CurrencySettings.vue
  frontend/src/components/Settings/General/HomeActions.vue
Labels: backport main-hotfix

#1262 chore: sync translations from crowdin
  crm/locale/nb.po
Labels: translation

#1282 fix: add validation for mandatory fields in useDocument
  frontend/src/data/document.js
  frontend/src/utils/index.js
Labels: backport main-hotfix

#1284 build(deps): bump frappeui to 0.1.201
  frontend/package.json
  frontend/yarn.lock
Labels: backport main-hotfix

#1289 chore: sync translations from crowdin
  crm/locale/nb.po
Labels: backport main-hotfix, translation
