Repository frappe/crm, pull requests merged in 2025-08, with the labels that each got.

#1103 chore: sync translations from crowdin
  crm/locale/fa.po
  crm/locale/id.po
Labels: translation

#1161 fix: More fixes
  frontend/src/components/Controls/GridFieldsEditorModal.vue
  frontend/src/components/Modals/ConvertToDealModal.vue
  frontend/src/components/SLASection.vue
Labels: backport main, backport main-hotfix

#1173 fix: reorder idx if grid row is reordered
  frontend/src/components/Controls/Grid.vue
  frontend/src/components/Settings/General/HomeActions.vue
Labels: backport main-hotfix

#1178 chore: update POT file
  crm/locale/main.pot
Labels: backport main-hotfix

#1179 chore: sync translations from crowdin
  crm/locale/id.po
  crm/locale/it.po
Labels: backport main-hotfix, translation

#1185 fix: remove "read only" flag for primary email, mobile & phone no
  crm/fcrm/doctype/crm_deal/crm_deal.json
Labels: backport main-hotfix

#1182 fix: do not allow saving public view kanban changes for non managers
  frontend/src/components/ViewControls.vue
Labels: backport main-hotfix
