Repository frappe/crm, pull requests merged in 2025-07, with the labels that each got.

#994 fix: Forecasting fixes
  crm/fcrm/doctype/crm_deal/crm_deal.py
  crm/fcrm/doctype/crm_deal_status/crm_deal_status.json
  crm/fcrm/doctype/crm_fields_layout/crm_fields_layout.py
  crm/fcrm/doctype/fcrm_settings/fcrm_settings.json
  crm/fcrm/doctype/fcrm_settings/fcrm_settings.py
  crm/install.py
  crm/patches.txt
  crm/patches/v1_0/update_deal_status_probabilities.py
  frontend/components.d.ts
  frontend/src/components/Modals/AddressModal.vue
  frontend/src/components/Modals/CallLogModal.vue
  frontend/src/components/Modals/ConvertToDealModal.vue
  frontend/src/data/document.js
  frontend/src/pages/Lead.vue
  frontend/src/utils/index.js
Labels: backport main-hotfix

#998 fix: show absolute day count not in decimals
  frontend/src/utils/index.js
Labels: backport main-hotfix

#1003 fix: add default lost reason on install
  crm/install.py
Labels: backport main-hotfix

#1009 fix: grid field is not getting set
  frontend/src/data/document.js
Labels: backport main-hotfix

#1013 refactor: Contact & Organization page
  crm/api/contact.py
  crm/fcrm/doctype/crm_deal/api.py
  crm/fcrm/doctype/crm_deal/crm_deal.json
  crm/fcrm/doctype/crm_lead/api.py
  frontend/src/components/SidePanelLayout.vue
  frontend/src/pages/Contact.vue
  frontend/src/pages/MobileContact.vue
  frontend/src/pages/MobileOrganization.vue
  frontend/src/pages/Organization.vue
Labels: backport main-hotfix

#1018 fix: set fieldname to handle bulk edit value modal
  frontend/src/components/Modals/EditValueModal.vue
Labels: backport main-hotfix

#979 feat: Dashboard
  crm/api/dashboard.py
  crm/api/session.py
  crm/fcrm/doctype/crm_deal/crm_deal.json
  crm/fcrm/doctype/crm_deal/crm_deal.py
  crm/fcrm/doctype/crm_organization/crm_organization.json
  crm/fcrm/doctype/crm_organization/crm_organization.py
  crm/fcrm/doctype/fcrm_settings/fcrm_settings.json
  crm/fcrm/doctype/fcrm_settings/fcrm_settings.py
  crm/utils/__init__.py
  frontend/components.d.ts
  frontend/src/components/Controls/Link.vue
  frontend/src/components/Layouts/AppSidebar.vue
  frontend/src/components/Settings/EmailAccountCard.vue
  frontend/src/components/Settings/EmailAccountList.vue
  frontend/src/components/Settings/EmailTemplate/EmailTemplates.vue
  frontend/src/components/Settings/General/BrandSettings.vue
  frontend/src/components/Settings/General/GeneralSettings.vue
  frontend/src/components/Settings/General/GeneralSettingsPage.vue
  frontend/src/components/Settings/General/HomeActions.vue
  frontend/src/components/Settings/Settings.vue
  frontend/src/components/Settings/TelephonySettings.vue
  frontend/src/components/Settings/Users.vue
  frontend/src/components/frappe-ui/Autocomplete.vue
  frontend/src/pages/Dashboard.vue
  frontend/src/router.js
  frontend/src/stores/users.js
  frontend/src/utils/dashboard.ts
Labels: backport main-hotfix

#1022 fix: apply user filter if sales user
  crm/api/dashboard.py
Labels: backport main-hotfix

#1036 fix: to status type is not accessible
  crm/fcrm/doctype/crm_status_change_log/crm_status_change_log.py
Labels: backport main-hotfix

#1038 fix: to status type is not accessible
  crm/fcrm/doctype/crm_status_change_log/crm_status_change_log.py
Labels: backport main-hotfix

#1041 fix: Reset to default dashboard
  crm/api/dashboard.py
  crm/integrations/exotel/handler.py
  frontend/src/pages/Dashboard.vue
Labels: backport main-hotfix

#1057 chore: sync translations from crowdin
  crm/locale/ar.po
  crm/locale/bs.po
  crm/locale/cs.po
  crm/locale/de.po
  crm/locale/es.po
  crm/locale/fa.po
  crm/locale/fr.po
  crm/locale/hr.po
  crm/locale/hu.po
  crm/locale/id.po
  crm/locale/it.po
  crm/locale/nl.po
  crm/locale/pl.po
  crm/locale/pt.po
  crm/locale/pt_BR.po
  crm/locale/ru.po
  crm/locale/sr.po
  crm/locale/sr_CS.po
  crm/locale/sv.po
  crm/locale/th.po
  crm/locale/tr.po
  crm/locale/vi.po
  crm/locale/zh.po
Labels: translation

#1059 refactor: Assignees logic
  crm/fcrm/doctype/crm_deal/crm_deal.py
  crm/utils/__init__.py
  frontend/src/data/document.js
Labels: backport main-hotfix

#1064 chore: sync translations from crowdin
  crm/locale/bs.po
  crm/locale/hr.po
Labels: backport main-hotfix, translation

#1068 fix: make mobile no primary on create of contact
  frontend/src/components/Modals/ContactModal.vue
Labels: backport main-hotfix

#1070 refactor: Call Log Button
  frontend/src/components/Activities/Activities.vue
  frontend/src/components/Activities/ActivityHeader.vue
  frontend/src/components/MultiActionButton.vue
Labels: backport main-hotfix

#1077 fix: Correct field name from 'agent' to 'user' in CRM Telephony Agent…
  crm/integrations/api.py
Labels: backport main-hotfix

#1084 fix: fixed labels
  frontend/src/components/Settings/General/CurrencySettings.vue
  frontend/src/components/Settings/General/GeneralSettings.vue
Labels: backport main-hotfix

#1094 Update init.sh
  docker/init.sh
  scripts/init.sh
Labels: backport main-hotfix

#1095 chore: sync translations from crowdin
  crm/locale/bs.po
  crm/locale/hr.po
  crm/locale/id.po
  crm/locale/sr.po
  crm/locale/sr_CS.po
  crm/locale/sv.po
Labels: backport main-hotfix, translation
